### ISSUE TITLE
User-definable voltage sweep range

### ISSUE THREAD

**Issue by rbrenesh** [greyltc/solar-sim-software#21]
Some users in our lab have asked if it would be possible to define the voltage sweep range, since some want to bias beyond Voc and below 0V. Don't know if this would be possible to add to the software?

Also, but not as critical as the above, to allow for some pre-biasing times.

**Comment by hollla** [comment]
![Figure_1](https://user-images.githubusercontent.com/10878363/65926361-e6fcd280-e3c2-11e9-94b8-fb78a3d14521.png)

having the ability to scan user-defined voltage is super important - currently, in some scans, it doesn't even pass both the Voc and Jsc, like the attached photo.

**Comment by greyltc** [comment]
Hi @hollla, thanks for the feedback!
and sorry @rbrenesh don't know how I missed this issue for so long!
I have good news: you can do this today.
Have a look at https://github.com/mutovis/control-software#usage
There you'll see
```
                       [--scan-low-override SCAN_LOW_OVERRIDE]
                       [--scan-high-override SCAN_HIGH_OVERRIDE]
```
You might have to play with the values you give there bit though before you get it right (if you don't like what you get just, swap them) this is because of the way the code I wrote accounts for NIP and PIN stacks.

When run without those above options, the program attempts to determine the start and stop scan voltages based on the Voc measurement: reverse scans go from Voc --> 0V and forward scans go from 0V --> Voc*1.2.

I've never seen a scan that doesn't achieve 0V. That seems pretty strange to me. I do think I include the 0V point in every sweep... Can you post the whole command you're running and I can have a look at recreating that problem here?
As for missing Voc, I can imagine a case where a reverse scan somehow doesn't start at Voc if the Voc determination didn't work so well for some reason (maybe it's a very hysteretic device? or maybe the steady state Voc measurement wasn't done for long enough?). I can't imagine a case where the forward sweep would ever miss Voc though since it should go well past.

**Comment by hollla** [comment]
Thank you @greyltc! ` [--scan-low-override SCAN_LOW_OVERRIDE]
                       [--scan-high-override SCAN_HIGH_OVERRIDE]` give me what I need.

This is what I run where I saw the scan didn't go both Jsc and Voc:

`mutovis-control --layout-index 12 --destination /home/onelab/data --pcb-address 192.168.1.11:23 --light-address ftdi://ftdi:232/1 --sm-address GPIB0::24::INSTR --rear true --four-wire on --pixel-address A1A2A3A4A5A6 --sweep on --snaith on --mppt 10 --mppt-params gradient_descent://0.001:0.001:10  -o DAK -r "buffalo thickness study" -p thickness 1.2m`

I did run the code on some cells with very minimal hysteresis and still observe the similar problem. 

Yes, it is possible it didn't do enough time of steady-state Voc measurement. With 10s of steady-state measurement, I mostly see the Voc is actually not fully stabilized (for example like attached photo).  
![Figure_1](https://user-images.githubusercontent.com/10878363/66166807-4eef2b00-e606-11e9-9c5e-8e28ccf459b5.png)

Anyway, thanks for the solution!
